name: pilot_workshop
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - statsmodels
  - scanpy